services:
  manon:
    image: ghcr.io/canopyflick/manon-pa-bot:latest
    container_name: manon
    volumes:
      - ./logger:/app/logger
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure:5

  manon_api:
    image: ghcr.io/canopyflick/manon-pa-bot:latest
    container_name: manon_api
    command: ["python", "-m", "api"]
    env_file:
      - .env
    ports:
      - "127.0.0.1:8787:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    container_name: manon_db
    restart: on-failure:5
    environment:
      POSTGRES_USER: manon
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: manon_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
